#!/usr/bin/env bash
# displaying loop 1 to 10 with lucks

i=1
while [ $i -lt 11 ]
do
if [ $i = 4 ]
then
echo "bad luck"
elif [ $i = 8 ]
then
echo "good luck"
else
echo "Best School"
fi
export i+=1
done
