#!/usr/bin/env bash
# displaying loop from 1 to 10 with luck
i=l
while [ $i -le 10 ] 
do
if  [ $i=8 ]
then
echo "good luck"
elif [ $i=4 ]
then
echo "Bad luck"
else
echo "Best School"
fi
i=$ ((i+1))
done
